# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sampleCML <- function(true_dag, df, targets, nodes_interest, names, lmax = 3L, signif_level = 0.01, verbose = TRUE, test = "testIndFisher", estDAG = FALSE) {
    .Call(`_CML_sampleCML`, true_dag, df, targets, nodes_interest, names, lmax, signif_level, verbose, test, estDAG)
}

popCML <- function(true_dag, targets, nodes_interest, names, lmax = 3L, verbose = TRUE) {
    .Call(`_CML_popCML`, true_dag, targets, nodes_interest, names, lmax, verbose)
}

sampleSNL <- function(true_dag, df, targets, nodes_interest, names, lmax = 3L, signif_level = 0.01, verbose = TRUE, test = "testIndFisher", estDAG = FALSE) {
    .Call(`_CML_sampleSNL`, true_dag, df, targets, nodes_interest, names, lmax, signif_level, verbose, test, estDAG)
}

popSNL <- function(true_dag, targets, nodes_interest, names, lmax = 3L, verbose = TRUE) {
    .Call(`_CML_popSNL`, true_dag, targets, nodes_interest, names, lmax, verbose)
}

getEdgeNumber <- function(G) {
    .Call(`_CML_getEdgeNumber`, G)
}

sharedNeighborhood <- function(reference, targets, i, j, verbose = FALSE) {
    .Call(`_CML_sharedNeighborhood`, reference, targets, i, j, verbose)
}

inTargetNeighborhood <- function(reference, targets, i, verbose = FALSE) {
    .Call(`_CML_inTargetNeighborhood`, reference, targets, i, verbose)
}

compareSkeletons <- function(est, truth, verbose = FALSE) {
    .Call(`_CML_compareSkeletons`, est, truth, verbose)
}

compareVStructures <- function(est, truth, verbose = FALSE) {
    .Call(`_CML_compareVStructures`, est, truth, verbose)
}

parentRecoveryAccuracy <- function(est, truth, targets, verbose = FALSE) {
    .Call(`_CML_parentRecoveryAccuracy`, est, truth, targets, verbose)
}

interNeighborhoodEdgeMetrics <- function(est, reference, true_dag, nbhd, verbose = FALSE) {
    .Call(`_CML_interNeighborhoodEdgeMetrics`, est, reference, true_dag, nbhd, verbose)
}

overallF1 <- function(est, ref, targets, verbose = FALSE) {
    .Call(`_CML_overallF1`, est, ref, targets, verbose)
}

allMetrics <- function(est, ref_graph, targets, true_dag, nbhd, verbose = FALSE, algo = "pc", which_nodes = "") {
    .Call(`_CML_allMetrics`, est, ref_graph, targets, true_dag, nbhd, verbose, algo, which_nodes)
}

getNeighborhoodMetrics <- function(G) {
    .Call(`_CML_getNeighborhoodMetrics`, G)
}

validateTargetSNL <- function(targets, t) {
    invisible(.Call(`_CML_validateTargetSNL`, targets, t))
}

combn_cpp <- function(x, l) {
    .Call(`_CML_combn_cpp`, x, l)
}

isMember <- function(x, i) {
    .Call(`_CML_isMember`, x, i)
}

getPartialCorrelation <- function(C, i, j, k) {
    .Call(`_CML_getPartialCorrelation`, C, i, j, k)
}

fisherZ <- function(pc, n, k_size) {
    .Call(`_CML_fisherZ`, pc, n, k_size)
}

condIndTest <- function(C, i, j, k, n, signif_level) {
    .Call(`_CML_condIndTest`, C, i, j, k, n, signif_level)
}

condIndTestPop <- function(G, i, j, k) {
    .Call(`_CML_condIndTestPop`, G, i, j, k)
}

matrix_to_string <- function(sep_vectors) {
    .Call(`_CML_matrix_to_string`, sep_vectors)
}

get_G2_one <- function(A, B, tot_Au_size, tot_Bu_size) {
    .Call(`_CML_get_G2_one`, A, B, tot_Au_size, tot_Bu_size)
}

get_G2_all <- function(A, B, S) {
    .Call(`_CML_get_G2_all`, A, B, S)
}

condInttestdis <- function(df, i, j, k, signif_level) {
    .Call(`_CML_condInttestdis`, df, i, j, k, signif_level)
}

initializeCML <- function(td, df, t, nodes_interest, names) {
    invisible(.Call(`_CML_initializeCML`, td, df, t, nodes_interest, names))
}

initializeCMLPop <- function(td, t, nodes_interest, names) {
    invisible(.Call(`_CML_initializeCMLPop`, td, t, nodes_interest, names))
}

getSizeCML <- function(td, df, t, nodes_interest, names) {
    .Call(`_CML_getSizeCML`, td, df, t, nodes_interest, names)
}

setSCML <- function(td, df, t, nodes_interest, names, i, j, k) {
    .Call(`_CML_setSCML`, td, df, t, nodes_interest, names, i, j, k)
}

setVerboseCML <- function(td, df, t, nodes_interest, names) {
    invisible(.Call(`_CML_setVerboseCML`, td, df, t, nodes_interest, names))
}

checkSkeletonTotal <- function(td, df, t, nodes_interest, names) {
    .Call(`_CML_checkSkeletonTotal`, td, df, t, nodes_interest, names)
}

checkSkeletonTotalPop <- function(td, t, nodes_interest, names) {
    .Call(`_CML_checkSkeletonTotalPop`, td, t, nodes_interest, names)
}

checkVStruct <- function(td, df, t, nodes_interest, names) {
    .Call(`_CML_checkVStruct`, td, df, t, nodes_interest, names)
}

checkVStructPop <- function(td, t, nodes_interest, names) {
    .Call(`_CML_checkVStructPop`, td, t, nodes_interest, names)
}

checkAdjMatConversion <- function(td, df, t, nodes_interest, names, m, neighbors) {
    .Call(`_CML_checkAdjMatConversion`, td, df, t, nodes_interest, names, m, neighbors)
}

checkNotationWarnings <- function(td, df, t, nodes_interest, names, m) {
    .Call(`_CML_checkNotationWarnings`, td, df, t, nodes_interest, names, m)
}

checkSeparationTest <- function(td, df, t, nodes_interest, names, i, j, l, nodes_to_skip) {
    .Call(`_CML_checkSeparationTest`, td, df, t, nodes_interest, names, i, j, l, nodes_to_skip)
}

checkCMLSummary <- function(td, df, targets, nodes_interest, names) {
    .Call(`_CML_checkCMLSummary`, td, df, targets, nodes_interest, names)
}

checkCMLSummaryPop <- function(td, targets, nodes_interest, names) {
    .Call(`_CML_checkCMLSummaryPop`, td, targets, nodes_interest, names)
}

testArmaCor <- function(M) {
    .Call(`_CML_testArmaCor`, M)
}

check_amat_works <- function(nodes, node_names, adj) {
    .Call(`_CML_check_amat_works`, nodes, node_names, adj)
}

check_amat_works_onepar <- function(nodes) {
    .Call(`_CML_check_amat_works_onepar`, nodes)
}

check_names_works <- function(nodes, node_names, adj) {
    .Call(`_CML_check_names_works`, nodes, node_names, adj)
}

check_dag_object <- function(nodes, node_names, adj, v = FALSE) {
    .Call(`_CML_check_dag_object`, nodes, node_names, adj, v)
}

check_pdag_object <- function(nodes, node_names, adj, v = FALSE) {
    .Call(`_CML_check_pdag_object`, nodes, node_names, adj, v)
}

check_dag_object2 <- function(nodes) {
    invisible(.Call(`_CML_check_dag_object2`, nodes))
}

check_pdag_object2 <- function(nodes) {
    invisible(.Call(`_CML_check_pdag_object2`, nodes))
}

check_neighbors_retrieval <- function(nodes, node_names, adj, t, v = FALSE) {
    .Call(`_CML_check_neighbors_retrieval`, nodes, node_names, adj, t, v)
}

check_neighbors_retrieval_multi <- function(nodes, node_names, adj, t, v = FALSE) {
    .Call(`_CML_check_neighbors_retrieval_multi`, nodes, node_names, adj, t, v)
}

check_pdag_neighbors_retrieval <- function(nodes, node_names, adj, t, v = FALSE) {
    .Call(`_CML_check_pdag_neighbors_retrieval`, nodes, node_names, adj, t, v)
}

check_amat_retrieval <- function(nodes, node_names, adj, i, j) {
    .Call(`_CML_check_amat_retrieval`, nodes, node_names, adj, i, j)
}

check_amat_retrieval_function <- function(nodes, node_names, adj, i, j) {
    .Call(`_CML_check_amat_retrieval_function`, nodes, node_names, adj, i, j)
}

check_amat_row_retrieval <- function(nodes, node_names, adj, i) {
    .Call(`_CML_check_amat_row_retrieval`, nodes, node_names, adj, i)
}

check_amat_col_retrieval <- function(nodes, node_names, adj, j) {
    .Call(`_CML_check_amat_col_retrieval`, nodes, node_names, adj, j)
}

check_adjacent_non_adjacent <- function(nodes, node_names, adj, i) {
    .Call(`_CML_check_adjacent_non_adjacent`, nodes, node_names, adj, i)
}

check_non_adjacent_solo <- function(nodes, node_names, adj, i) {
    .Call(`_CML_check_non_adjacent_solo`, nodes, node_names, adj, i)
}

check_directed_undirected <- function(nodes, node_names, adj, i, j) {
    .Call(`_CML_check_directed_undirected`, nodes, node_names, adj, i, j)
}

check_sizes <- function(nodes, node_names, adj) {
    .Call(`_CML_check_sizes`, nodes, node_names, adj)
}

check_amat_setval <- function(nodes, node_names, adj, i, j, val) {
    .Call(`_CML_check_amat_setval`, nodes, node_names, adj, i, j, val)
}

check_amat_setval_function <- function(nodes, node_names, adj, i, j, val) {
    .Call(`_CML_check_amat_setval_function`, nodes, node_names, adj, i, j, val)
}

checkIfAdjacent <- function(nodes, node_names, adj, i, j) {
    .Call(`_CML_checkIfAdjacent`, nodes, node_names, adj, i, j)
}

checkEmptyGraph <- function(p) {
    .Call(`_CML_checkEmptyGraph`, p)
}

checkAcyclicity <- function(nodes, node_names, adj) {
    .Call(`_CML_checkAcyclicity`, nodes, node_names, adj)
}

checkIsAncestor <- function(nodes, node_names, adj, desc, anc, verbose = FALSE) {
    .Call(`_CML_checkIsAncestor`, nodes, node_names, adj, desc, anc, verbose)
}

checkInNeighborhood <- function(nodes, node_names, adj, i, j, verbose = FALSE) {
    .Call(`_CML_checkInNeighborhood`, nodes, node_names, adj, i, j, verbose)
}

check_pdag_inNeighborhood <- function(nodes, node_names, adj, i, j, verbose = FALSE) {
    .Call(`_CML_check_pdag_inNeighborhood`, nodes, node_names, adj, i, j, verbose)
}

check_set_amat <- function(nodes, node_names, adj) {
    .Call(`_CML_check_set_amat`, nodes, node_names, adj)
}

check_disc_path <- function(nodes, node_names, adj, c, d, e) {
    .Call(`_CML_check_disc_path`, nodes, node_names, adj, c, d, e)
}

check_upd_path <- function(nodes, node_names, adj, a, b, e) {
    .Call(`_CML_check_upd_path`, nodes, node_names, adj, a, b, e)
}

test_checkWronglyCovered <- function(nodes, node_names, adj, p) {
    invisible(.Call(`_CML_test_checkWronglyCovered`, nodes, node_names, adj, p))
}

checkNeighborhoodId <- function(nodes, node_names, adj, i, verbose = FALSE) {
    .Call(`_CML_checkNeighborhoodId`, nodes, node_names, adj, i, verbose)
}

testInitializeMBList <- function(nodes, mb_mat) {
    invisible(.Call(`_CML_testInitializeMBList`, nodes, mb_mat))
}

testInitializeMBListPop <- function(nodes, amat) {
    invisible(.Call(`_CML_testInitializeMBListPop`, nodes, amat))
}

testAccessMB <- function(nodes, mb_mat, i) {
    .Call(`_CML_testAccessMB`, nodes, mb_mat, i)
}

testAccessMultipleMB <- function(nodes, mb_mat, v, include_targets = FALSE, exclude_targets = FALSE, verbose = FALSE) {
    .Call(`_CML_testAccessMultipleMB`, nodes, mb_mat, v, include_targets, exclude_targets, verbose)
}

testIsMBMember <- function(nodes, mb_mat, target, i) {
    .Call(`_CML_testIsMBMember`, nodes, mb_mat, target, i)
}

testSilencer <- function(nodes, mb_mat, target, i) {
    invisible(.Call(`_CML_testSilencer`, nodes, mb_mat, target, i))
}

test_union <- function(x, y) {
    .Call(`_CML_test_union`, x, y)
}

test_sort <- function(x) {
    .Call(`_CML_test_sort`, x)
}

test_fill <- function(nrow, ncol, value) {
    .Call(`_CML_test_fill`, nrow, ncol, value)
}

test_fill_diag <- function(x, value) {
    .Call(`_CML_test_fill_diag`, x, value)
}

test_create <- function(x1, x2) {
    .Call(`_CML_test_create`, x1, x2)
}

test_setdiff <- function(v1, v2) {
    .Call(`_CML_test_setdiff`, v1, v2)
}

test_intersect <- function(v1, v2) {
    .Call(`_CML_test_intersect`, v1, v2)
}

test_map_insert <- function(v1, v2) {
    .Call(`_CML_test_map_insert`, v1, v2)
}

test_map_find <- function(v1, v2, a) {
    invisible(.Call(`_CML_test_map_find`, v1, v2, a))
}

test_sep_arma <- function() {
    .Call(`_CML_test_sep_arma`)
}

test_subset_mat <- function(m, i) {
    .Call(`_CML_test_subset_mat`, m, i)
}

test_NumMat_value <- function(G) {
    .Call(`_CML_test_NumMat_value`, G)
}

test_decrement_matrix <- function(G) {
    invisible(.Call(`_CML_test_decrement_matrix`, G))
}

testRule1 <- function(td, dummy_df, dummy_t, names, m) {
    .Call(`_CML_testRule1`, td, dummy_df, dummy_t, names, m)
}

testRule2 <- function(td, dummy_df, dummy_t, names, m) {
    .Call(`_CML_testRule2`, td, dummy_df, dummy_t, names, m)
}

testRule3 <- function(td, dummy_df, dummy_t, names, m) {
    .Call(`_CML_testRule3`, td, dummy_df, dummy_t, names, m)
}

testRule4 <- function(td, dummy_df, dummy_t, names, m, i, j, k) {
    .Call(`_CML_testRule4`, td, dummy_df, dummy_t, names, m, i, j, k)
}

testRule8 <- function(td, dummy_df, dummy_t, names, m) {
    .Call(`_CML_testRule8`, td, dummy_df, dummy_t, names, m)
}

testRule9 <- function(td, dummy_df, dummy_t, names, m) {
    .Call(`_CML_testRule9`, td, dummy_df, dummy_t, names, m)
}

testRule10 <- function(td, dummy_df, dummy_t, names, m) {
    .Call(`_CML_testRule10`, td, dummy_df, dummy_t, names, m)
}

testAllRules <- function(td, dummy_df, dummy_t, names, m) {
    .Call(`_CML_testAllRules`, td, dummy_df, dummy_t, names, m)
}

testConvertMixed <- function(td, t, names, m, v) {
    .Call(`_CML_testConvertMixed`, td, t, names, m, v)
}

checkInitializeSNL <- function(td, df, t, nodes_interest, names) {
    .Call(`_CML_checkInitializeSNL`, td, df, t, nodes_interest, names)
}

checkGetTargetSkel <- function(td, df, t, nodes_interest, names) {
    .Call(`_CML_checkGetTargetSkel`, td, df, t, nodes_interest, names)
}

checkGetVStructures <- function(td, df, t, nodes_interest, names) {
    .Call(`_CML_checkGetVStructures`, td, df, t, nodes_interest, names)
}

checkInitializeSNLPop <- function(td, t, nodes_interest, names) {
    .Call(`_CML_checkInitializeSNLPop`, td, t, nodes_interest, names)
}

checkGetTargetSkelPop <- function(td, t, nodes_interest, names) {
    .Call(`_CML_checkGetTargetSkelPop`, td, t, nodes_interest, names)
}

checkGetVStructuresPop <- function(td, t, nodes_interest, names) {
    .Call(`_CML_checkGetVStructuresPop`, td, t, nodes_interest, names)
}

checkRule1 <- function(td, test_mat, t, nodes_interest, names) {
    .Call(`_CML_checkRule1`, td, test_mat, t, nodes_interest, names)
}

checkRule2 <- function(td, test_mat, t, nodes_interest, names) {
    .Call(`_CML_checkRule2`, td, test_mat, t, nodes_interest, names)
}

checkRule3 <- function(td, test_mat, t, nodes_interest, names) {
    .Call(`_CML_checkRule3`, td, test_mat, t, nodes_interest, names)
}

checkRule4 <- function(td, test_mat, t, nodes_interest, names) {
    .Call(`_CML_checkRule4`, td, test_mat, t, nodes_interest, names)
}

checkSNLRules <- function(td, test_mat, t, nodes_interest, names) {
    .Call(`_CML_checkSNLRules`, td, test_mat, t, nodes_interest, names)
}

checkSNL <- function(td, df, t, nodes_interest, names) {
    .Call(`_CML_checkSNL`, td, df, t, nodes_interest, names)
}

checkSNLRun <- function(td, df, t, nodes_interest, names) {
    .Call(`_CML_checkSNLRun`, td, df, t, nodes_interest, names)
}

checkSNLPop <- function(td, t, nodes_interest, names) {
    .Call(`_CML_checkSNLPop`, td, t, nodes_interest, names)
}

getNbhd <- function(p, node_names, adj, targets, verbose) {
    .Call(`_CML_getNbhd`, p, node_names, adj, targets, verbose)
}

printS <- function(neighbors) {
    invisible(.Call(`_CML_printS`, neighbors))
}

getInitialValues <- function(neighbors, i, j) {
    .Call(`_CML_getInitialValues`, neighbors, i, j)
}

setListEmptySet <- function(neighbors, i, j) {
    .Call(`_CML_setListEmptySet`, neighbors, i, j)
}

setListEfficient <- function(neighbors, i, j, kvals) {
    .Call(`_CML_setListEfficient`, neighbors, i, j, kvals)
}

checkSeparationFunc <- function(neighbors, i, j, sep, val_to_check) {
    .Call(`_CML_checkSeparationFunc`, neighbors, i, j, sep, val_to_check)
}

checkSeparationFuncCorrected <- function(neighbors, i, j, sep, val_to_check) {
    .Call(`_CML_checkSeparationFuncCorrected`, neighbors, i, j, sep, val_to_check)
}

checkIsSepSetMember <- function(neighbors, i, j, sep1, sep2, val_to_check) {
    .Call(`_CML_checkIsSepSetMember`, neighbors, i, j, sep1, sep2, val_to_check)
}

checkPotentialVStruct <- function(neighbors, i, j, sep, k) {
    .Call(`_CML_checkPotentialVStruct`, neighbors, i, j, sep, k)
}

checkGetS <- function(neighbors, i, j, sep) {
    .Call(`_CML_checkGetS`, neighbors, i, j, sep)
}

